# Frontend
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keptn-demo
  description: Keptn Project
  tags:
    - keptn
  links:
    - url: https://github.com/maurosala/keptn-demo
      title: "keptn-demo"
      icon: "dashboard"
  annotations:
    github.com/project-slug: maurosala/keptn-demo
    backstage.io/techdocs-ref: dir:.
    keptn.sh/service: demo
    keptn.sh/project: krateo
spec:
  type: service
  lifecycle: experimental
  owner: "kerberus"
